// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA08KIDrdDZ4mS0O66u3H-v1VR85vSGe58',
    appId: '1:942819761945:web:df617d0a1a1bd696f52f88',
    messagingSenderId: '942819761945',
    projectId: 'holotrade-app',
    authDomain: 'holotrade-app.firebaseapp.com',
    storageBucket: 'holotrade-app.firebasestorage.app',
    measurementId: 'G-GP6V6QLX0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_jmTH0AB1E-ij0vErKe0SbeQ2s9aLCI',
    appId: '1:942819761945:android:2bc484a52af7687ef52f88',
    messagingSenderId: '942819761945',
    projectId: 'holotrade-app',
    storageBucket: 'holotrade-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdz8wq9oMNsE0Q82gWkFRyw8SOm7I42J8',
    appId: '1:942819761945:ios:2eab0511a3cca83ef52f88',
    messagingSenderId: '942819761945',
    projectId: 'holotrade-app',
    storageBucket: 'holotrade-app.firebasestorage.app',
    iosBundleId: 'com.example.stockTradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdz8wq9oMNsE0Q82gWkFRyw8SOm7I42J8',
    appId: '1:942819761945:ios:2eab0511a3cca83ef52f88',
    messagingSenderId: '942819761945',
    projectId: 'holotrade-app',
    storageBucket: 'holotrade-app.firebasestorage.app',
    iosBundleId: 'com.example.stockTradingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA08KIDrdDZ4mS0O66u3H-v1VR85vSGe58',
    appId: '1:942819761945:web:b948a12e2b83ee2bf52f88',
    messagingSenderId: '942819761945',
    projectId: 'holotrade-app',
    authDomain: 'holotrade-app.firebaseapp.com',
    storageBucket: 'holotrade-app.firebasestorage.app',
    measurementId: 'G-52XPW4BLRB',
  );
}
